"""empty message

Revision ID: 045fce8e2e82
Revises: eb065a6b31be
Create Date: 2017-09-04 16:58:05.896358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045fce8e2e82'
down_revision = 'eb065a6b31be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('image_url', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'image_url')
    # ### end Alembic commands ###
